### ISSUE TITLE
FAILURE_TIMESTAMP_TOO_FAR_IN_FUTURE

### ISSUE THREAD

**Issue by NimbusCs** [44uk/nem-ruby#14]
i try to make transactions and i get:

"Message: FAILURE_TIMESTAMP_TOO_FAR_IN_FUTURE"
"TransactionHash: 9886eb467932e7b62a2f10f3b8f8cfaa56195bf3c3792b01bfd9f4afd8c89e5f"

**Comment by 44uk** [comment]
> To get network time from a node, use <NODE_DOMAIN>/time-sync/network-time api and divide sendTimeStamp by 1000.
https://forum.nem.io/t/topic/19254/11?u=44uk
