### ISSUE TITLE
Why does the transfer function only support integers numbers? What happens if one needs to work with XEM fractions?

### ISSUE THREAD

**Issue by NimbusCs** [44uk/nem-ruby#8]

**Comment by 44uk** [comment]
You can send fractions xem.

```
tx = Nem::Transaction::Transfer.new(B_ADDRESS, 0.01, 'Good luck! send by nem-ruby')
```

http://bob.nem.ninja:8765/#/transfer/7ef44ab16dfb355675db1c5b27ca3091f3ee99333a85d70781e1fea9f47351ef

```
tx = Nem::Transaction::Transfer.new(B_ADDRESS, 0.000001, 'Good luck! send by nem-ruby')
```

http://bob.nem.ninja:8765/#/transfer/2577ef9f42959c1c9f7c37f61e71fd33e706778082025b956a963a6e3df7a0e7

**Comment by NimbusCs** [comment]
i try:

tx = Nem::Transaction::Transfer.new(B_ADDRESS, 9.85, 'reeeeeeeeeee')

and the following error appears:

undefined method `>>' for 9850000.0:Float Did you mean? >

nem-ruby (0.0.10) lib/nem/util/serializer.rb:168:in `block in serialize_long'


Extracted source (around line #168): 

        bin = sprintf('%040b', value)
        0.upto(bin.size / 8 - 1) do |i|
          **a[i] = 0xFF & (value >> 8 * i)**
        end
        a
      end

**Comment by 44uk** [comment]
It was bug but already fixed. Please use v0.0.11
