### ISSUE TITLE
is possible get transaction hash from NIS or this gem?

### ISSUE THREAD

**Issue by JokerCatz** [44uk/nem-ruby#9]
is possible get transaction hash from NIS or this gem?

I can't get transaction hash (like btc : txid or eth : txhash) without broadcast , & I can't get it from NIS API like `/block/at/public` too ( if I want get it without from my account or offline sign ) ... anybody can help me or use another SDKs ?

**Comment by 44uk** [comment]
you can get /transaction/get?hash=abcdefg....

or using this https://github.com/44uk/nem-ruby/blob/master/examples/endpoint/transaction.rb#L10

see [How to get a transaction data with NIS API? - Tech Support - NEM Forum](https://forum.nem.io/t/how-to-get-a-transaction-data-with-nis-api/3130/2).

**Comment by 44uk** [comment]
Try this above example.
